import type { Metadata } from "next";
import { Geist, Geist_Mono, Jaldi } from "next/font/google";
import "./globals.css";

// Next.js seems to require this to be assigned even though it is never used
// eslint-disable-next-line @typescript-eslint/no-unused-vars
const jaldi = Jaldi({
  weight: ["400", "700"]
});

const jaldi = Jaldi({
  variable: "--font-jaldi",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${jaldi.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
