import type { Metadata } from "next";
import { Jaldi } from "next/font/google";
import "./globals.css";
import RefreshHandler from "./components/RefreshHandler";
import Navbar from "./components/navbar/navbar";
import Footer from "./components/footer/footer";

// Next.js seems to require this to be assigned even though it is never used
// eslint-disable-next-line @typescript-eslint/no-unused-vars
const jaldi = Jaldi({
  weight: ["400", "700"],
  subsets: ["devanagari", "latin", "latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <RefreshHandler></RefreshHandler>
      <body className="font-jaldi flex min-h-dvh flex-col antialiased">
        <Navbar></Navbar>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
