DROP FUNCTION IF EXISTS filter_photos;
DROP TABLE IF EXISTS event;
DROP TABLE IF EXISTS phototag;
DROP TABLE IF EXISTS tag;
DROP TABLE IF EXISTS photo;
DROP TABLE IF EXISTS blog;
DROP TABLE IF EXISTS photoclubuser;
